config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { edit: 'profile/edit' }, controllers: {registrations: 'users/registrations' }
  root to: redirect('index')

  get 'index', to: 'games#index', as: 'games'
  get 'index/:game_id', to: 'listings#index', as: 'game'
  post 'index/:game_id', to: 'listings#create'
  get 'index/:game_id/new', to: 'listings#new', as: 'new_game_listing'

  get 'listings/new', to: 'listings#alt_new', as: 'new_listing' # enable for new listing + search game
  post 'listings', to: 'listings#create_listing', as: 'listings' # enable for new listnig + search game

  get 'listing/:listing_id/offers', to: 'offers#index', as: 'offers'
  get 'listing/:listing_id/offers/new', to: 'offers#new', as: 'new_offer'
  get 'listing/:listing_id/offers/new/games_index', to: 'offers#games_index', as: 'games_index' # used for WF06 'Choose from a list'
  post 'listing/:listing_id/offers', to: 'offers#create'
  delete 'listing/:listing_id/offers/:id', to: 'offers#destroy', as: 'cancel_offer'

  get 'profile/:profile_id', to: 'profiles#show', as: 'profile' # routes for my_offers, incoming_offers, listings, trade_history
  get 'profile/:profile_id/offers', to: 'offers#index', as: 'my_offers'
  get 'profile/:profile_id/listings', to: 'listings#home', as: 'my_listings'


  get 'profile/:profile_id/listings/:id/edit', to: 'listings#edit', as: 'edit_listing'
  get 'profile/:profile_id/listings/:id', to: 'listings#show', as: 'show_listing'
  patch 'profile/:profile_id/listings/:id', to: 'listings#update'
  delete 'profile/:profile_id/listings/:id', to: 'listings#destroy'

  get 'profile/:profile_id/listings/:id/offers', to: 'listings#listing_offers', as: 'listing_offers'
  patch 'profile/:profile_id/listings/:listing_id/offers/:id', to: 'listings#accept_decline', as: 'listing_offer'

  get 'profile/:profile_id/history', to: 'history#index', as: 'trade_history'
  get 'profile/:profile_id/history/:offer_id/:rating', to: 'history#new_rating', as: 'new_rating'

  resources :games do
    collection do
      post :search
    end
  end




end

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  id          :bigint           not null, primary key
#  condition   :string
#  description :text
#  status      :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  game_id     :bigint
#  user_id     :bigint
#
# Indexes
#
#  index_listings_on_game_id  (game_id)
#  index_listings_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (game_id => games.id)
#  fk_rails_...  (user_id => users.id)
#
class Listing < ApplicationRecord

    has_many(
        :offers,
        class_name: "Offer",
        foreign_key: "listing_id",
        inverse_of: :listing,
        # dependent: :destroy
    )

    belongs_to(
        :user,
        class_name: 'User',
        foreign_key: 'user_id',
        inverse_of: :listings
    )

    belongs_to(
        :game,
        class_name: 'Game',
        foreign_key: 'game_id',
        inverse_of: :listings
    )
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

    def index
      @game = Game.find(params[:game_id])
      @listings = @game.listings
      render :index
    end

    def home
      @owner= User.find(params[:profile_id])
      @listings = @owner.listings
      render :home
    end


    def new
      @game = Game.find(params[:game_id])
      @listing = Listing.new
      render :new
    end

    # enable to integrate game searching into new listings, route currently disabled
    # def alt_new
    #   @listing = Listing.new
    #   render :alt_new
    # end

    # disabled -- obsolete, created when testing new listings + game searching
    # def create_listing
    #   @game = Game.find(params[:game_id])
    #   @listing= @game.listings.build(params.require(:listing).permit(:condition, :description))
    #   @listing.user=current_user
    #   @listing.status="active"
    #     if @listing.save!
    #       flash[:success] = "Listing saved successfully"
    #       redirect_to game_url(@game)
    #   else
    #       flash.now[:error] = "Listing could not be saved"
    #       render :new, status: :unprocessable_entity
    #     end
    # end

    def create
      @game = Game.find(params[:game_id])
      @listing= @game.listings.build(params.require(:listing).permit(:condition, :description))
      @listing.user=current_user
      @listing.status="active"
        if @listing.save!
          flash[:success] = "Listing saved successfully"
          redirect_to game_url(@game)
      else
          flash.now[:error] = "Listing could not be saved"
          render :new, status: :unprocessable_entity
        end
    end

    def edit
      @owner= current_user
      @listing = @owner.listings.find(params[:id])
      render :edit
    end

    def show
      @owner=User.find(params[:profile_id])
      @listing = Listing.find(params[:id])
      render :show
    end

    def listing_offers
      @user=User.find(params[:profile_id])
      @listing = Listing.find(params[:id])
      @offers=@listing.offers
      render :listing_offers
    end

    def accept_decline
      @user=User.find(params[:profile_id])
      @listing = Listing.find(params[:listing_id])
      @offers=@listing.offers
      @offer=@listing.offers.find(params[:id])

      if params[:status]=="Accept"
        @listing.update!(status:"inactive")
        @offers.each do |offer|
          offer.update!(status: "declined")
        end
        @offer.update!(status:"accepted")
        flash[:success] = "Offer successfully accepted"
        redirect_to my_listings_path(@user)
      elsif params[:status]=="Decline"
        @offer.update!(status:"declined")
        flash[:success] = "Offer successfully declined"
        redirect_to listing_offers_path(@user, @listing)
      end
    end

    def update
      @owner = current_user
      @listing= @owner.listings.find(params[:id])
      if @listing.update(params.require(:listing).permit(:condition, :description))
        flash[:success] = "Listing updated successfully"
        redirect_to my_listings_path(@owner)
      else
        flash.now[:error] = "Listing could not be updated"
        render :edit, status: :unprocessable_entity
      end
    end


    def destroy
      @owner = User.find(params[:profile_id])
      @listing= @owner.listings.find(params[:id])
      @listing.destroy
      flash[:success] = "Listing deleted successfully"
      redirect_to my_listings_path(@owner), status: :see_other
    end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/alt_new.html.erb
<div class="container w-50 mx-auto">
  <h1> New Game Listing</h1>
  <div class="row gap-2">
    <div class="form-control row border-0">
      <%= render "games/search_form" %>
    </div>
    <div id="search_results" class="row"></div>
  </div>

  <%= bootstrap_form_with model: @listing, method: :post, class: 'row g-3', url: listings_path, data: {turbo: false} do |f| %>
    <div class="row form-control border-0">
      <%= f.select :condition, ["New", "Used-Like New", "Used-Very Good", "Used-Good", "Used-Acceptable"] %>
    </div>
     <div class="form-control border-0 row">
       <%= f.text_area :description, :rows => 2, placeholder: "Describe the condition and what you would like to trade for" %>
    </div>
    <div class="d-grid form-control gap-2 border-0">
      <div class="d-grid col-3 mx-auto">
        <%#= f.submit %>
      </div>
      <div class="d-grid col-3 mx-auto">
        <%= link_to 'Cancel', games_path(), class: 'btn btn-outline-secondary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/listings/edit.html.erb
<div class="container text-center mx-auto">
    <h1> Edit Game Listing</h1>

    <h3><%=@listing.game.title%></h3>

    <%= image_tag "covers/" + @listing.game.image, size: '400x520' %>


  <%= bootstrap_form_with model: @listing, method: :patch, url: show_listing_path(@owner, @listing), data: { turbo: false } do |f| %>
    <%= f.select :condition, ["New", "Used-Like New", "Used-Very Good", "Used-Good", "Used-Acceptable"]%>
    <%= f.text_field :description%>
    <%= f.submit %>
  <% end %>

  <p class="mt-3">
    <%= button_to 'Delete Listing', show_listing_path(@owner, @listing), method: :delete, data: { turbo: false }, class: 'btn btn-outline-secondary ', form: { class: 'd-inline' } %>
    <br><br>
    <%= link_to 'Cancel', my_listings_path(@owner), class: 'btn btn-outline-secondary' %>
  </p>

</div>

app/views/listings/home.html.erb
 <%= render "shared/header" %>
    <head>
        <title></title>
    </head>
        <h3>Listings</h3>
        <table class="table table-striped">
            <thead class="table table-dark">
                <tr>
                    <th>Game Title</th>
                    <th>Game Condition</th>
                    <th>Description</th>
                    <% if @owner==current_user%>
                    <th>No. of Offers</th>
                    <th><!-- Edit Listing --></th>
                    <th><!-- View My Offers --></th>
                    <%else%>
                    <th><!-- Make Offer --></th>
                    <th></th>
                    <%end%>
                </tr>
            <thead>
            <tbody>
                    <% @listings.each do |listing| %>
                    <% if listing.status=="active"%>
                    <tr>
                        <td><%= listing.game.title %></td>
                        <td><%= listing.condition %></td>
                        <td><%= listing.description%></td>
                        <% if listing.user==current_user%>
                        <td><%= listing.offers.where(status: 'active').size%></td>
                        <td><%= link_to "Edit Listing", edit_listing_path(current_user, listing), class: 'btn btn-outline-secondary'%></td>
                        <td><%= link_to "View Offers", listing_offers_path(current_user, listing),class: 'btn btn-outline-secondary'%></td>
                        <% else %>
                        <td><%= link_to 'Make Offer', new_offer_path(listing.id), class: 'btn btn-primary' %><td>
                        <% end %>
                    </tr>
                    <% end %>
                <% end %>
            </tbody>
        </table>

app/views/listings/index.html.erb
<style>
      .container {
        display: flex;
        align-items: center;
        justify-content: center
      }
      .image {
        flex-basis: 30%
      }
      .text {
        font-size: 20px;
        padding-left: 20px;
      }
      .text2 {
        text-align: right;
      }
      table {
        border-collapse: separate;
        border-spacing: 0 10px;
      }
    </style>

<div class="max-w-lg mr-auto mt-16 text-center">
 <h1><%= @game.title %></h1>
</div>


<div class="container">
    <div class="image">
    <%= image_tag "covers/" + @game.image, size: '400x520' %>
    </div>
    <div class="text">
          <%= @game.description%>
    </div>
</div>

 <div class="container-fluid">
    <div class="row align-items-center">
        <div class="col-md-8">
            <h1> Trades </h1>
        </div>
        <div class="col-6 col-md-4 text-end">
            <%= link_to 'Create New Listing', new_game_listing_path, class: 'btn btn-primary' %>
        </div>
    </div>
</div>

<table class="table table-striped">
  <thead class="table-dark">
    <tr>
      <th style="width:80%">Username</th>
      <th>Condition</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @listings.each_with_index do |listing, index| %>
      <tr>
        <td><%= index+1 %>. <%= link_to listing.user.username, my_listings_path(listing.user)%><br></td>
        <td><%= listing.condition%></td>
        <td>
        <% if listing.user != current_user %><!-- only display make new offer for other users -->
          <%= link_to 'Make Offer', new_offer_path(listing.id), class: "btn btn-primary" %>
        <% end %>
        </td>
      </tr>
      <tr>
        <td><%= listing.description%></td>
        <td></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/listings/listing_offers.html.erb
<h3> <%= @listing.game.title %> </h3>
<div class="row", style="background-color:black; color:white">
    <div class="col-md-1">Username</div>
    <div class="col-md-2">Game Name</div>
    <div class="col-md-2">Condition</div>
    <div class="col-5">Description</div>
    <div class="col-md-1"><!-- Accept --></div>
    <div class="col-md-1"><!-- Decline --></div>
</div>
<% @offers.each do |offer| %>
    <%= form_with model: offer, method: :patch, url: listing_offer_path(current_user.id, @listing, offer), data: { turbo: false } do |f| %>
        <div class="row">
        <% if offer.status=="active" %>
            <div class="col-md-1"><%=link_to offer.owner.username, my_listings_path(offer.owner)%></div>
            <div class="col-md-2"><%=offer.game.title %></div>
            <div class="col-md-2"><%=offer.condition %></div>
            <div class="col-5"><%=offer.description %></div>
            <div class="col-sm-1"><%=f.submit "Accept",  name: "status", class: 'btn btn-success'%></div>
            <div class="col-sm-1"><%=f.submit "Decline", name: "status",  class: 'btn btn-danger'%></div>
            <hr size="3" width="100%" color="black"> 
            <% end %>
        </div>
    <% end %>
<% end %>
   

app/views/listings/new.html.erb
<div class="container text-center w-50 mx-auto">
  <h1> New Game Listing</h1>
  <h3><%=@game.title%></h3>
  <%= image_tag "covers/" + @game.image, size: '400x520' %>

  <div class="row gap-2">
    <div class="form-control row border-0">
      <%= render "games/search_form" %>
    </div>
    <div id="search_results" class="row"></div>
  </div>

  <%= bootstrap_form_with model: @listing, method: :post, class: 'row g-3', url: game_path(@game), data: {turbo: false} do |f| %>
    <div class="row form-control border-0">
      <%= f.select :condition, ["New", "Used-Like New", "Used-Very Good", "Used-Good", "Used-Acceptable"] %>
    </div>
     <div class="form-control border-0 row">
       <%= f.text_area :description, :rows => 2, placeholder: "Describe the condition and what you would like to trade for" %>
    </div>
    <div class="d-grid form-control gap-2 border-0">
      <div class="d-grid col-3 mx-auto">
        <%= f.submit %>
      </div>
      <div class="d-grid col-3 mx-auto">
        <%= link_to 'Cancel', game_path(@game), class: 'btn btn-outline-secondary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/listings/show.html.erb
<style>
      .container {
        display: flex;
        align-items: center;
        justify-content: center
      }
      .image {
        flex-basis: 30%
      }
      .text {
        font-size: 20px;
        padding-left: 20px;
      }
</style>
<div class="max-w-lg mr-auto mt-16 text-center">
  <h1><%= @listing.game.title %></h1>
</div>


<div class="container">
    <div class="image">
    <%= image_tag "covers/" + @listing.game.image, size: '400x520' %>
    </div>
    <div class="text">
          <%= "Condition: "+ @listing.condition%>
          <br><br>
          <%= "Description: "+ @listing.description%>
    </div>
</div>