config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { edit: 'profile/edit' }, controllers: {registrations: 'users/registrations' }
  root to: redirect('index')

  get 'index', to: 'games#index', as: 'games'
  get 'index/:game_id', to: 'listings#index', as: 'game'
  post 'index/:game_id', to: 'listings#create'
  get 'index/:game_id/new', to: 'listings#new', as: 'new_game_listing'

  get 'listings/new', to: 'listings#alt_new', as: 'new_listing' # enable for new listing + search game
  post 'listings', to: 'listings#create_listing', as: 'listings' # enable for new listnig + search game

  get 'listing/:listing_id/offers', to: 'offers#index', as: 'offers'
  get 'listing/:listing_id/offers/new', to: 'offers#new', as: 'new_offer'
  get 'listing/:listing_id/offers/new/games_index', to: 'offers#games_index', as: 'games_index' # used for WF06 'Choose from a list'
  post 'listing/:listing_id/offers', to: 'offers#create'
  delete 'listing/:listing_id/offers/:id', to: 'offers#destroy', as: 'cancel_offer'

  get 'profile/:profile_id', to: 'profiles#show', as: 'profile' # routes for my_offers, incoming_offers, listings, trade_history
  get 'profile/:profile_id/offers', to: 'offers#index', as: 'my_offers'
  get 'profile/:profile_id/listings', to: 'listings#home', as: 'my_listings'


  get 'profile/:profile_id/listings/:id/edit', to: 'listings#edit', as: 'edit_listing'
  get 'profile/:profile_id/listings/:id', to: 'listings#show', as: 'show_listing'
  patch 'profile/:profile_id/listings/:id', to: 'listings#update'
  delete 'profile/:profile_id/listings/:id', to: 'listings#destroy'

  get 'profile/:profile_id/listings/:id/offers', to: 'listings#listing_offers', as: 'listing_offers'
  patch 'profile/:profile_id/listings/:listing_id/offers/:id', to: 'listings#accept_decline', as: 'listing_offer'

  get 'profile/:profile_id/history', to: 'history#index', as: 'trade_history'
  get 'profile/:profile_id/history/:offer_id/:rating', to: 'history#new_rating', as: 'new_rating'

  resources :games do
    collection do
      post :search
    end
  end




end

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert <%= alert_class(key) %> alert-dismissible fade show m-0" role="alert">
    <div class="text-center alert-message"><%= message %></div>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<html>
    <head>
        <title></title>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-3 text-center" id="picture and name">
                    <% @user = User.find(params[:profile_id]) %>
                    <%= image_tag @user.image, class: "img-fluid w-50 rounded-circle" %>
                    <br>
                    <%= @user.username %>
                </div>
                <div class="col-6" id="rating_description">
                    Rating: <%= @user.get_rating > 0 ? @user.get_rating : "none" %><br>
                    <p><%= @user.description %></p>
                    <% if @user == current_user %>
                        <%= link_to "Edit Profile", edit_user_registration_path%>
                    <% end %>
                </div>
                <div class="col-3" id="offers_trade_history">
                    <% if @user == current_user %>
                        <ul class="list-group mt-3">
                            <%= link_to 'My Listings', my_listings_path(@user.id), class: 'list-group-item list-group-item-action fs-6' %>
                            <%= link_to "My Offers", my_offers_path(@user.id), class: 'list-group-item list-group-item-action fs-6' %>
                            <%= link_to "Trade History", trade_history_path(@user.id), class: 'list-group-item list-group-item-action fs-6' %>
                        </ul>
                    <% end %>
                </div>
            </div>
        </div>
    </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar bg-light border-bottom border-dark m-0 sticky-top">
  <div class="container-fluid">
    <%= link_to games_path do %>
      <%= image_tag 'logos/gameswap.png', class: "d-inline-block align-text-top", style: "height: 2.5rem;"%>
    <% end %>

    
    <div class="d-flex btn-group">
      <% if user_signed_in? %>
        <%= link_to href=my_listings_path(current_user) do %>
          <%= image_tag current_user.image, class: 'btn btn-outline-dark', height: '38'  %>
        <% end %>        
        <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'btn btn-outline-dark' %>
      <% else %>
        <%= link_to 'Sign In', new_user_session_path, class: "btn btn-outline-dark #{active_class(new_user_session_path)}" %>
        <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-outline-dark #{active_class(new_user_registration_path)}" %>
      <% end %>
    </div>

  </div>
</nav>