config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { edit: 'profile/edit' }, controllers: {registrations: 'users/registrations' }
  root to: redirect('index')

  get 'index', to: 'games#index', as: 'games'
  get 'index/:game_id', to: 'listings#index', as: 'game'
  post 'index/:game_id', to: 'listings#create'
  get 'index/:game_id/new', to: 'listings#new', as: 'new_game_listing'

  get 'listings/new', to: 'listings#alt_new', as: 'new_listing' # enable for new listing + search game
  post 'listings', to: 'listings#create_listing', as: 'listings' # enable for new listnig + search game

  get 'listing/:listing_id/offers', to: 'offers#index', as: 'offers'
  get 'listing/:listing_id/offers/new', to: 'offers#new', as: 'new_offer'
  get 'listing/:listing_id/offers/new/games_index', to: 'offers#games_index', as: 'games_index' # used for WF06 'Choose from a list'
  post 'listing/:listing_id/offers', to: 'offers#create'
  delete 'listing/:listing_id/offers/:id', to: 'offers#destroy', as: 'cancel_offer'

  get 'profile/:profile_id', to: 'profiles#show', as: 'profile' # routes for my_offers, incoming_offers, listings, trade_history
  get 'profile/:profile_id/offers', to: 'offers#index', as: 'my_offers'
  get 'profile/:profile_id/listings', to: 'listings#home', as: 'my_listings'


  get 'profile/:profile_id/listings/:id/edit', to: 'listings#edit', as: 'edit_listing'
  get 'profile/:profile_id/listings/:id', to: 'listings#show', as: 'show_listing'
  patch 'profile/:profile_id/listings/:id', to: 'listings#update'
  delete 'profile/:profile_id/listings/:id', to: 'listings#destroy'

  get 'profile/:profile_id/listings/:id/offers', to: 'listings#listing_offers', as: 'listing_offers'
  patch 'profile/:profile_id/listings/:listing_id/offers/:id', to: 'listings#accept_decline', as: 'listing_offer'

  get 'profile/:profile_id/history', to: 'history#index', as: 'trade_history'
  get 'profile/:profile_id/history/:offer_id/:rating', to: 'history#new_rating', as: 'new_rating'

  resources :games do
    collection do
      post :search
    end
  end




end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id          :bigint           not null, primary key
#  description :text
#  image       :string
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  tag_id      :bigint
#
# Indexes
#
#  index_games_on_tag_id  (tag_id)
#
# Foreign Keys
#
#  fk_rails_...  (tag_id => tags.id)
#
class Game < ApplicationRecord
    validates :title, :image, :description, presence: true
    validates :title, uniqueness: true

    belongs_to(
        :tag,
        class_name: 'Tag',
        foreign_key: 'tag_id',
        inverse_of: :games
    )

    has_many(
        :listings,
        class_name: 'Listing',
        foreign_key: 'game_id',
        inverse_of: :game,
        dependent: :destroy
    )

    has_many(
        :offers,
        class_name: 'Offer',
        foreign_key: 'game_id',
        inverse_of: :game,
        dependent: :destroy
    )



end

app/controllers/games_controller.rb
class GamesController < ApplicationController

   def index
      @q = Game.ransack(params[:q])
      @games = @q.result.includes(:tag, :listings).order(:title)
      @tags = Tag.all.order(:name)
      render :index
   end

   def search
      @games = Game.where('title ILIKE ?', "%#{params[:title_search]}%") # search query for title passing search_field text
      @listing = params[:listing_id]
      params[:title_search]
      respond_to do |format|
         format.turbo_stream do
            render turbo_stream: turbo_stream.update("search_results",
               partial: "games/search_results", locals: {games: @games, listing: @listing}) # partial view "_search_results.html.erb"
         end
      end
   end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_search_form.html.erb
<%= bootstrap_form_with url: search_games_path, method: :post do |f| %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= hidden_field_tag :listing_id, params[:listing_id] %> <%# pass listing_id for new offer compliance %>
    <%= hidden_field_tag :searching_from_url, request.original_url %> <%# used to check between new offer/new game; passing because search built using partials %>
    <% if params[:game_id] %> <%# if there's a game title, insert it as a placeholder in the form field or else display an instructional prompt %>
        <% placeholder_string = Game.find(params[:game_id]).title %>
    <% else %>
        <% placeholder_string = "Search for a game by title..." %>
    <% end %>
    <%= f.search_field :title_search, oninput: "this.form.requestSubmit()", label: "Game title", value: placeholder_string %>
<% end %>
<div id="search_results"><%# search results displayed here %></div>

app/views/games/_search_results.html.erb
<div class="list-group">
  <% @games.take(5).each do |g| %>
    <div class="row">
      <div class="col md-100">
        <button type="button" class="list-group-item list-group-item-action" data-bs-toggle="collapse" data-bs-target="#g<%= g.id.to_s %>" aria-expanded="false" aria-controls="g<%= g.id.to_s %>">
          <%= g.title %>
        </button>
      </div>
      <div class="col-1"> <%# to-do set this column to fixed size%>
        <%# if params[:listing_id] != "" and params[:searching_from_url] == new_offer_url(params[:listing_id]) %> <%# short circuit if listing_id is empty %>
        <% if params[:listing_id] != "" and params[:searching_from_url].match(new_offer_url(params[:listing_id])) %> <%# short circuit if listing_id is empty, if searching_from_url (<url>?game=game_id) contains a portion of new_offer_url (<url>) %>
          <%# new offer %>
          <%= link_to "Offer", new_offer_path(params[:listing_id], :game_id => g.id), class: 'btn btn-sm btn-primary mt-1' %>
        <% else %>
          <%# new listing %>
          <%= link_to "List", new_game_listing_path(:game_id => g.id), class: 'btn btn-sm btn-primary mt-1' %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <div class="collapse multi-collapse" id="g<%= g.id.to_s %>">
          <div class="card card-body">
            <%# expandable information, can format however %>
            <%= g.tag.name %><br>
            <%= truncate(g.description, :length => 256) %>
          </div>
        </div>
      </div>
      <div class="col-1"><%# format %></div>
    </div>
  <% end %>
</div>

app/views/games/index.html.erb
<div class="container text-center m-3">

    <%= search_form_for @q do |f| %>
        <div class="input-group mb-3">
            <%= f.search_field :title_cont, class: 'form-control form-control-md', placeholder: 'Search Games' %>
            <%= f.submit class:'btn btn-outline-secondary'%>
        </div>
    <% end %>

</div>


<div class="container-fluid">
    <div class="container-fluid row">
        <div class="col col-2">
            <div class="row p-2"><%# change styling/spacing as desired %>
                <div class="col">
                    <%= link_to "Create New Listing", new_listing_path(), class: 'btn btn-primary btn-med' %>
                </div>
            </div>
            <div class="row p-2">
                <%= search_form_for @q, class: do |f| %>
                    <h3><strong>Genre</strong></h3>

                    <div class="form-check">
                        <%= f.radio_button :tag_name_cont, '', {class: 'form-check-input fs-6', oninput: "this.form.requestSubmit()"} %>
                        <%= f.label 'All', class: 'form-check-label fs-6' %>
                    </div>

                    <% @tags.each do |tag| %>
                        <div class="form-check">
                            <%= f.radio_button :tag_name_cont, tag.name, {class: 'form-check-input fs-6', oninput: "this.form.requestSubmit()"} %>
                            <%= f.label tag.name, class: 'form-check-label fs-6' %>
                        </div>
                    <% end %>

                    <div class="form-check form-switch">
                        <%= f.check_box :listings_id_not_null, {class: 'form-check-input fs-6', oninput: "this.form.requestSubmit()"}, 1, nil %>
                        <%= f.label "Games with listings", class: 'form-label fs-6'%>
                    </div>
                    
                <% end %>
            </div>
        </div>
        <!-- Games container -->
        <div class="container col text-center">
            <div class="container row row-cols-auto gap-3 m-auto ">
                <% @games.each do |game| %>

                    <div class="col m-auto">

                        <%= link_to href= game_path(game), class: 'text-decoration-none' do %>

                            <div class="card" style="width: 15rem;">
                                <%= image_tag "covers/" + game.image, class: "card-img-top", size: '175x280'   %>
                                <div class="card-body bg-light">
                                    <p class="card-text" style="font-size: 13px"><%= game.title %> </p>
                                </div>
                            </div>
                        <% end %>
                    </div>

                <% end %>
                <% if @games.count == 0%>
                    <p>No Games Found</p>
                <% end %>
            </div>
        </div>
    </div>
</div>