config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { edit: 'profile/edit' }, controllers: {registrations: 'users/registrations' }
  root to: redirect('index')

  get 'index', to: 'games#index', as: 'games'
  get 'index/:game_id', to: 'listings#index', as: 'game'
  post 'index/:game_id', to: 'listings#create'
  get 'index/:game_id/new', to: 'listings#new', as: 'new_game_listing'

  get 'listings/new', to: 'listings#alt_new', as: 'new_listing' # enable for new listing + search game
  post 'listings', to: 'listings#create_listing', as: 'listings' # enable for new listnig + search game

  get 'listing/:listing_id/offers', to: 'offers#index', as: 'offers'
  get 'listing/:listing_id/offers/new', to: 'offers#new', as: 'new_offer'
  get 'listing/:listing_id/offers/new/games_index', to: 'offers#games_index', as: 'games_index' # used for WF06 'Choose from a list'
  post 'listing/:listing_id/offers', to: 'offers#create'
  delete 'listing/:listing_id/offers/:id', to: 'offers#destroy', as: 'cancel_offer'

  get 'profile/:profile_id', to: 'profiles#show', as: 'profile' # routes for my_offers, incoming_offers, listings, trade_history
  get 'profile/:profile_id/offers', to: 'offers#index', as: 'my_offers'
  get 'profile/:profile_id/listings', to: 'listings#home', as: 'my_listings'


  get 'profile/:profile_id/listings/:id/edit', to: 'listings#edit', as: 'edit_listing'
  get 'profile/:profile_id/listings/:id', to: 'listings#show', as: 'show_listing'
  patch 'profile/:profile_id/listings/:id', to: 'listings#update'
  delete 'profile/:profile_id/listings/:id', to: 'listings#destroy'

  get 'profile/:profile_id/listings/:id/offers', to: 'listings#listing_offers', as: 'listing_offers'
  patch 'profile/:profile_id/listings/:listing_id/offers/:id', to: 'listings#accept_decline', as: 'listing_offer'

  get 'profile/:profile_id/history', to: 'history#index', as: 'trade_history'
  get 'profile/:profile_id/history/:offer_id/:rating', to: 'history#new_rating', as: 'new_rating'

  resources :games do
    collection do
      post :search
    end
  end




end

app/models/offer.rb
# == Schema Information
#
# Table name: offers
#
#  id          :bigint           not null, primary key
#  condition   :string
#  description :string
#  status      :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  game_id     :bigint
#  listing_id  :bigint
#  user_id     :bigint
#
# Indexes
#
#  index_offers_on_game_id     (game_id)
#  index_offers_on_listing_id  (listing_id)
#  index_offers_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (game_id => games.id)
#  fk_rails_...  (listing_id => listings.id)
#  fk_rails_...  (user_id => users.id)
#
class Offer < ApplicationRecord
  belongs_to(
    :listing,
    class_name: 'Listing',
    foreign_key: 'listing_id',
    inverse_of: :offers
  )

  belongs_to(
    :game,
    class_name: 'Game',
    foreign_key: 'game_id',
    inverse_of: :offers
  )

  belongs_to(
    :owner,
    class_name: 'User',
    foreign_key: 'user_id',
    inverse_of: :offers
  )

  has_many(
    :ratings,
    class_name: 'Rating',
    foreign_key: 'offer_id',
    inverse_of: :offer,
    dependent: :destroy
  )

  validates :accepted, presence: false # allow, initialize offers with nil until they're accepted/declined?
  validates :condition, inclusion: { in: %W(New #{"Used-Like New"} #{"Used-Very Good"} Used-Good Used-Acceptable), message: "%{value} is not a valid condition"} # using %W(#{"terms with spaces"}) for clarity, otherwise %w() allows escape
  validates :status, inclusion: { in: %w(active accepted declined), message: "{value} is not a valid status"}
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :authenticate_user!, except: [:games_index]
  before_action :require_permission, except: [:games_index, :new, :index, :destroy]

  def require_permission
    @listing = Listing.find(params[:listing_id]) # do not allow Listing owners to make offers on their own listings
    if @listing.user == current_user # user, not owner
      flash[:error] = "You do not have permission to do that"
      redirect_to game_path(Listing.find(params[:listing_id]).game_id)
    end
  end

  def index
    @owner = User.find(params[:profile_id])
    @offers = @owner.offers
    render :index
  end

  # disallow rendering this page if it listing_id doesn't exist/wasn't accessed via link on offers/new.html.erb
  def games_index # used for WF06, 'Choose from a list' possibly move route, action to another controller
    @q = Game.ransack(params[:q])
    @games = @q.result.includes(:tag).order(:title)
    @tags = Tag.all.order(:name)
    render :games_index
  end

  def new
    @all = Game.all
    @listing = Listing.find(params[:listing_id])
    if params[:game_id]
      @offer = Offer.new(:game_id => params[:game_id])
    else
      @offer = Offer.new
    end
    @user = current_user

    render :new
  end

  def create
    @listing = Listing.find(params[:listing_id])
    @game = Game.where(title: params[:title])[0] # must use first index because .where() returns an array of all matching games; there should be only one
    @offer = current_user.offers.build(params.require(:offer).permit(:condition, :description)) # tried permitting :title here, also assigning @game_id => Game.where(params.permit[:title]), and many other variations
    if @game != nil # @game, therefore game_id must exist in order to save it; if this fails, @offer.save will fail and flash an error
      @offer.game_id = @game.id
    end
    @offer.listing_id = @listing.id
    @offer.status = "active" # required
    # note that accepted attribute is initially nil
    if @offer.save
      flash[:success] = "Offer successfully created"
      redirect_to games_path()
    else
      flash.now[:error] = "Unable to save new offer"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @listing = Listing.find(params[:listing_id])
    @offer = Offer.find(params[:id])
    @offer.destroy
    flash[:success] = "Offer successfully canceled"
    redirect_to my_offers_path(current_user), status: :see_other
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/games_index.html.erb
<div class="container-fluid row mt-5">

    <h1 class='text-center'>Choose a game for your offer</h1>

    <div class="col col-2">
        <h2 class='text-center'>Genre</h2>
        <%= search_form_for @q, url: games_index_path do |f| %>

            <div class="form-check">
                <%= f.radio_button :tag_name_cont, '', {class: 'form-check-input fs-6', oninput: "this.form.requestSubmit()"} %>
                <%= f.label 'All', class: 'form-check-label fs-6' %>
            </div>

            <% @tags.each do |tag| %>
                <div class="form-check">
                    <%= f.radio_button :tag_name_cont, tag.name, {class: 'form-check-input fs-6', oninput: "this.form.requestSubmit()"} %>
                    <%= f.label tag.name, class: 'form-check-label fs-6' %>
                </div>
            <% end %>

        <% end %>
    </div>

    <div class="container col-8">
        <%= search_form_for @q, url: games_index_path do |f| %>
            <div class="input-group mb-3"> 
                <%= f.search_field :title_cont, class: 'form-control form-control-md', placeholder: 'Search Games' %>
                <%= f.submit class:'btn btn-outline-secondary'%>
            </div>
        <% end %>

        <table class="table table-hover border border-dark table fs-6">
            <thead class="table-secondary"> 
                <tr>
                    <th><%= sort_link(@q, :title, 'Game Name') %></th>
                    <th><%= sort_link(@q, :tag_name, 'Genre') %></th>
                </tr>
            </thead>

            <tbody>
                <% @games.each do |g| %>
                    <tr>
                        <td> <%= link_to g.title, new_offer_path(:listing_id => params[:listing_id], :game_id => g) %></td>
                        <td><%= g.tag.name %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>    
    </div>  

</div>

app/views/offers/index.html.erb
   <html>
    <head>
        <title></title>
    </head>
    <body>
        <!-- include user header here via views/layouts/application.html.erb conditional checking current_page?(path) -->
        <%= render "shared/header" %>
        <h3>My Offers</h3>
        <table class="table table-striped"> <!-- styling to match previously created index, can change as necessary -->
            <thead class="table table-dark">
                <tr>
                    <th>Game They Have</th>
                    <th>Game You Have</th>
                    <th>Description</th>
                    <th><!-- Cancel Offer column --></th>
                </tr>
            <thead>
            <tbody>
                <% @offers.each do |o| %>
                <% if o.status=="active" %>
                    <tr>
                        <td><%= o.listing.game.title %></td>
                        <td><%= o.game.title %></td>
                        <td><%= o.description %></td>
                        <td><%= button_to "Cancel Offer", cancel_offer_path(o.listing.id, o.id), method: :delete, data: { turbo: false } %></td>
                    </tr>
                    <% end %>
                <% end %>
            </tbody>
        </table>
    </body>
</html>

app/views/offers/new.html.erb
    <div class="container">
        <div class="row">
            <div class="col">
                <h1 style="text-align: center">New Offer</h1>
            </div>
        </div>
        <div class="row ">
            <div class="col-5">
                <!-- Listing -->
                <%= image_tag "covers/" + @listing.game.image, class: 'card-img-top', size: '525x640'  %>
                <h2><%= @listing.game.title %></h2>
                <p>Condition: <%= @listing.condition %></p>
                <p><%= @listing.description %></p>
            </div>
            <div class="col-2" align="center">
                <div class="row h-25"><!-- formatting --></div>
                <div class="row">
                    <%# <div class="align-self-start"> %>
                        <%= image_tag "logos/logo1.png", class: 'card-img'%>
                    <%# </div> %>
                </div>
                <div class="row h-50"><!-- formatting --></div>
                <div>
                    <div class="col">
                        <input type="submit" value="Create Offer" form="new_offer_form" %> <!-- submit button outside of form tags by id -->
                        <%= link_to "Cancel", game_path(Listing.find(params[:listing_id]).game_id), class: 'btn btn-secondary d-block' %>
                    </div>
                </div>
            </div>
            <div class="col-5">
                <!-- Offer -->
                <% if params[:game_id] %>
                    <% offer_game_title = Game.find(params[:game_id]).title %>
                    <%= image_tag "covers/" + Game.find(params[:game_id]).image, class: 'card-img-top', size: '525x640' %>  <%# placeholder for dynamic image %>
                <% else %>
                    <%= image_tag "covers/NO_COVER.png", class: 'bg-img', size: '525x640' %>
                <% end %>
                <%= render "games/search_form" %>
                <%= bootstrap_form_with id: "new_offer_form", model: @offer, url: offers_path, method: :post, data: { turbo: false } do |f| %> <%# probably a more streamlined way to use form fields outside of a block, but this works %>

                    <%= hidden_field_tag :title, offer_game_title %>

                    <%# pass listing_id to games_index so it can redierct back to this page (using the correct listing_id that the offer is being made for) %>
                    <%= link_to "Show All Games", games_index_path(:listing_id => params[:listing_id]), class: 'btn btn-primary rounded-pill mt-2' %>
                    <%= f.select :condition, %W(New #{"Used-Like New"} #{"Used-Very Good"} Used-Good Used-Acceptable) %>
                    <%= f.text_area :description, placeholder: "This game is in mint condition..." %>
                <% end %>
            </div>
        </div>
    </div>